# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# GitLab
# Browse to the hostname and login 
# Username: root 
# Password: 5iveL!fe

$script = <<SCRIPT
sudu apt-get update -y
wget https://downloads-packages.s3.amazonaws.com/ubuntu-14.04/gitlab_7.1.1-omnibus-1_amd64.deb
sudo apt-get install openssh-server -y
sudo apt-get install postfix -y
sudo dpkg -i gitlab_7.1.1-omnibus-1_amd64.deb
sudo -e /etc/gitlab/gitlab.rb
sudo gitlab-ctl reconfigure
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/20140813/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.synced_folder "../gitlab", "/home/vagrant/gitalb",
    create: true, owner: "vagrant", group: "vagrant"
  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.provision "shell", inline: $script
end
