# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
docker run -i -p 3000:80 -t ryosy383/kandan /bin/bash
SCRIPT


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "kandan"
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder "../kandan_share",  "/home/vagrant/kandan_share",
    create: true, owner: "vagrant", group: "vagrant"

  config.vm.provision :docker do |d|
    d.pull_images "ryosy383/kandan"
  end

  config.vm.network :private_network, ip: "192.168.1.200"
  config.vm.provision "shell", inline: $script
end
 
